---
openapi: 3.0.1
info:
  title: Consumer connectivity
  description: |
    #### Copyright
    © Aeris Communications, Inc. 2026. All rights reserved. No part of this document may be reproduced in any form without the written permission of the copyright owner.

    #### Disclaimer

    The contents of this document are subject to revision without notice due to continued progress in methodology, design and manufacturing.
    Aeris shall have no liability for any error or damage of any kind resulting from the use of this document.

    #### Trademark List

    All trademarks mentioned herein are the property of their respective owners.
    These are shown in the document Trademark Information.

    # Introduction

    This document describes the IoT Accelerator Consumer Connectivity API that provides
    resources to manage consumer owned data balances, products, purchases, recurring purchases, and subscriptions.
    The Consumer Connectivity API is based on the Representational State Transfer (REST) interface.
    From this point on, the Consumer Connectivity API is referred to as API in this document.

    ## Scope

    This document covers the following topics:

    — An overview of the API

    — A detailed description of all operations offered by the API

    ## Prerequisites
    In this document, it is assumed that the user is familiar with the following:

    — Java Script Object Notation (JSON)

    — Basic understanding of REST web services

    — The [OpenAPI Initiative](https://www.openapis.org/) for the standardized format used in this document.

    ## Related Information
    The definition and explanation of acronyms and terminology and typographic conventions can be found in the following documents:

    — IoTA Glossary of Terms and Acronyms

    — Typographic Conventions

    # General API Guidelines

    ## Compatibility

    API audience must be prepared for compatible API extensions:

    - Be tolerant with unknown fields in the payload (see also Fowler’s "TolerantReader" post), i.e. ignore new fields but do not eliminate them from payload if needed for subsequent PUT requests.
    - Be prepared that "x-extensible-enum" return parameter may deliver new values. Either be agnostic or provide default behavior for unknown values.
    - Be prepared to handle HTTP status codes not explicitly specified in endpoint definitions.
    - Follow the redirect when the server returns HTTP status 301 Moved Permanently.

    ## Security

    This section describes the security measures in the API. Security measures include authentication, authorization, and encryption.

    ### Authentication and Authorization

    The API uses OAuth2 and OpenID Connect (OIDC) for authentication and authorization.

    All API endpoints require authentication, which is performed by passing a token in the Authorization header in each request, preceded by the word Bearer and a space. See the following example:
    ```
    curl -i -X GET "http://<baseURL>/iot/api/consumer-connectivity/subscriptions/IMSI/<A_Specific_IMSI>" -H "Accept: application/vnd.dcp-v1+json" -H "Authorization: Bearer <TOKEN_GOES_HERE>"
    ```
    To fetch the token using e.g. curl, submit the following:
    ```
    curl -X POST "https://<baseURL>/iot/api/auth/token" -H "Accept: application/vnd.dcp-v1+json" -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=password&client_id=<client_id>&username=<username>&password=<password>"
    ```
    ### Encryption

    All API requests are encrypted using the HTTPS protocol to grant secure data transfer.

    
    ## Deprecation

    API deprecation will be reflected in the OpenAPI definition. If a method on a path, a whole path or even a whole API endpoint (multiple paths) should be deprecated, they will be marked as deprecated.
    During deprecation phase, a Warning header (see RFC 7234 - Warning header) field will be added in the response. The warn-code will be 299 and the warn-text will inform about what is deprecated and when it will be completely removed.

    API audience should not start using a deprecated API.

    API audience is encouraged to monitor for Warning header.
  version: 2.0.1
  x-api-id: 7d04b81f-0545-4c01-9d81-244fda13b6c8
  x-audience: external-public
servers:
  - url: https://iot-api.aeris.com/iot/api/consumer-connectivity
    description: API server
security:
  - Oauth2_auth: []
paths:
  /data-balances/{company-id}/{subscription-id-type}/{subscription-id}:
    get:
      tags:
        - Data balances
      summary: Get data balance of a subscription.
      description: Returns data balance of a subscription.
      operationId: getDataBalanceBySubscription
      security:
        - Oauth2_auth:
            - cc.read
  /products:
    put:
      tags:
        - Products
      summary: Update product for a company.
      description: Updates a product for a company.
      operationId: updateProduct
      security:
        - Oauth2_auth:
            - cc.write
    post:
      tags:
        - Products
      summary: Create a new product for a company.
      description: Creates a new product for a company.
      operationId: createProduct
      security:
        - Oauth2_auth:
            - cc.write
  /products/{company-id}:
    get:
      tags:
        - Products
      summary: List products of a company.
      description: Lists products of a company.
      operationId: getProductsByCompany
      security:
        - Oauth2_auth:
            - cc.read
  /products/{company-id}/{product-id}:
    get:
      tags:
        - Products
      summary: Get a product of a company.
      description: Returns a product of a company.
      operationId: getProductById
      security:
        - Oauth2_auth:
            - cc.read
  /products/{company-id}/properties/values:
    get:
      tags:
        - Products
      summary: Get product property values of a company.
      description: Returns valid product property values of a company.
      operationId: getProductPropertyValues
      security:
        - Oauth2_auth:
            - cc.read
  /purchases/{company-id}/{subscription-id-type}/{subscription-id}/{purchase-id}:
    get:
      tags:
        - Purchases
      summary: Get a purchase of a subscription.
      description: Returns a purchase of a subscription.
      operationId: getPurchase
      security:
        - Oauth2_auth:
            - cc.read
  /purchases/{company-id}/{subscription-id-type}/{subscription-id}/free:
    post:
      tags:
        - Purchases
      summary: Purchase a free product.
      description: Purchases a free product.
      operationId: purchaseFree
      security:
        - Oauth2_auth:
            - cc.write
  /purchases/{company-id}/{subscription-id-type}/{subscription-id}/refund:
    put:
      tags:
        - Purchases
      summary: Refund a purchase of a subscription.
      description: Refunds a purchase of a subscription.
      operationId: refundPurchase
      security:
        - Oauth2_auth:
            - cc.write
  /purchases/buckets/{company-id}/{subscription-id-type}/{subscription-id}/{purchase-id}:
    delete:
      tags:
        - Purchases
      summary: Delete a bucket of a subscription.
      description: Deletes a bucket of a subscription by purchase ID.
      operationId: deleteBucket
      security:
        - Oauth2_auth:
            - cc.write
  /purchases/{company-id}/{subscription-id-type}/{subscription-id}:
    get:
      tags:
        - Purchases
      summary: List purchases of a subscription.
      description: Lists purchases of a subscription.
      operationId: getPurchasesBySubscription
      security:
        - Oauth2_auth:
            - cc.read
    post:
      tags:
        - Purchases
      summary: Purchase a product.
      description: Purchases a product.
      operationId: purchase
      security:
        - Oauth2_auth:
            - cc.read
  /recurring-purchases/{company-id}/{subscription-id-type}/{subscription-id}/pause:
    put:
      tags:
        - Recurring purchases
      summary: Pause or resume a recurring purchase of a subscription.
      description: Pauses or resumes a recurring purchase of a subscription.
      operationId: pauseRecurringPurchase
      security:
        - Oauth2_auth:
            - cc.write
  /recurring-purchases/{company-id}/{subscription-id-type}/{subscription-id}/free:
    put:
      tags:
        - Recurring purchases
      summary: Set free recurring purchases for a subscription.
      description: Sets free recurring purchases for a subscription.
      operationId: freeRecurringPurchases
      security:
        - Oauth2_auth:
            - cc.write
  /recurring-purchases/{company-id}/{subscription-id-type}/{subscription-id}:
    get:
      tags:
        - Recurring purchases
      summary: List active recurring purchases of a subscription.
      description: Lists active recurring purchases of a subscription.
      operationId: getRecurringPurchasesBySubscription
      security:
        - Oauth2_auth:
            - cc.read
  /recurring-purchases/{company-id}/{subscription-id-type}/{subscription-id}/{purchase-id}:
    delete:
      tags:
        - Recurring purchases
      summary: Cancel recurring purchase of a subscription.
      description: Cancels recurring purchases of a subscription.
        Data bucket will not be deleted
      operationId: deleteRecurringPurchase
      security:
        - Oauth2_auth:
            - cc.write
  /subscriptions/{subscription-id-type}/{subscription-id}:
    get:
      tags:
        - Subscriptions
      summary: Get a subscription.
      description: Returns a subscription.
      operationId: getSubscription
      security:
        - Oauth2_auth:
            - cc.read
  /subscriptions/reset:
    put:
      tags:
        - Subscriptions
      summary: Reset a subscription.
      description: Resets a subscription.
      operationId: resetSubscription
      security:
        - Oauth2_auth:
            - cc.write
components:
  securitySchemes:
    Oauth2_auth:
      flows:
        password:
          tokenUrl:
            https://iot-api.aeris.com/iot/api/auth/token
          scopes:
            cc.read: |-
              Access right needed to read from Consumer Connectivity service.
            cc.write: |-
              Access right needed to write to Consumer Connectivity service.
      type: oauth2