---
openapi: 3.0.2
info:
  version: 0.2.2
  title: 'Incident Management API'
  description: |
    #### Copyright 
    © Aeris Communications, Inc. 2026. All rights reserved. No part of this document may be reproduced in any form without the written permission of the copyright owner.
    
    #### Disclaimer

    The contents of this document are subject to revision without notice due to continued progress in methodology, design and manufacturing.
    Aeris shall have no liability for any error or damage of any kind resulting from the use of this document.
    
    #### Trademark List

    All trademarks mentioned herein are the property of their respective owners.These are shown in the document Trademark Information.
    
    # Introduction
    
    ** This document describes the IoT Accelerator Incidents Management API that provides Incidents resources to retrieve an organization's Incidents information. The Incidents Management API is based on the Representational State Transfer (REST) interface. From this point on, the Incidents Management API is referred to as API in this document.**********
    
    ## Scope
    This document covers the following topics:

    — An overview of the API

    — A detailed description of all operations offered by the API

    ## Prerequisites
    In this document, it is assumed that the user is familiar with the following:

    — Java Script Object Notation (JSON)

    — Basic understanding of REST web services

    — The [OpenAPI Initiative](https://www.openapis.org/) for the standardized format used in this document.

    ## Related Information
    The definition and explanation of acronyms and terminology and typographic conventions can be found in the following documents:

    — IoTA Glossary of Terms and Acronyms

    — Typographic Conventions

    # General API Guidelines

    ## Compatibility

    API audience must be prepared for compatible API extensions:

    - Be tolerant with unknown fields in the payload (see also Fowler’s "TolerantReader" post), i.e. ignore new fields but do not eliminate them from payload if needed for subsequent PUT requests.
    - Be prepared that "x-extensible-enum" return parameter may deliver new values. Either be agnostic or provide default behavior for unknown values.
    - Be prepared to handle HTTP status codes not explicitly specified in endpoint definitions.
    - Follow the redirect when the server returns HTTP status 301 Moved Permanently.

    ## Security

    This section describes the security measures in the API. Security measures include authentication, authorization, and encryption.

    ### Authentication and Authorization

    The API uses OAuth2 and OpenID Connect (OIDC) for authentication and authorization.

    All API endpoints require authentication, which is performed by passing a token in the Authorization header in each request, preceded by the word Bearer and a space. See the following example:
    ```
    curl -i -X GET "http://<baseURL>/iot/api/ts/incidents" -H "Content-Type: application/json" -H "Authorization: Bearer <TOKEN_GOES_HERE>"
    
    ```
    To fetch the token using e.g. curl, submit the following:
    ```
    curl -X POST "https://<baseURL>/iot/api/auth/token" -H "Accept: application/vnd.dcp-v1+json" -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=password&client_id=<client_id>&username=<username>&password=<password>"
    ```
    ### Encryption

    All API requests are encrypted using the HTTPS protocol to grant secure data transfer.

    
    ## Deprecation

    API deprecation will be reflected in the OpenAPI definition. If a method on a path, a whole path or even a whole API endpoint (multiple paths) should be deprecated, they will be marked as deprecated.
    During deprecation phase, a Warning header (see RFC 7234 - Warning header) field will be added in the response. The warn-code will be 299 and the warn-text will inform about what is deprecated and when it will be completely removed.

    API audience should not start using a deprecated API.

    API audience is encouraged to monitor for Warning header.
    
  x-audience: external-partner
  x-api-id: 0a3ec0e4-3765-4a4f-8caa-b42ecb8e0d26
servers:
  - url: https://iot-api.aeris.com/iot/api/ts
    description: API server
    
paths:
  '/incidents/search':
    post:
      tags:
        - Incidents
      summary: Search for incidents
      description: A list of recent incidents in brief representation.
      operationId: searchIncidents
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise


  '/incidents':
    get:
      tags:
        - Incidents
      summary: List incidents
      description: A list of up to 200 recent incidents in brief representation.
      operationId: listIncidents
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise
    post:
      tags:
        - Incidents
      summary: Create incident
      description: Create a new incident in Ticketing Service.
      operationId: createIncident
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise
            - css_premium_csp_incident_for_operators

  '/incidents/{incident_id}':

    get:      
      summary: Incident with activities
      tags:
        - Incidents
      
      description: This resource contains a complete representation of an incident with all activities and attachment metadata.
      operationId: getIncident
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise

  '/incidents/{incident_id}/status':
    get:
      tags:
        - Incidents
      summary: Incident status
      description: This resource contains the current status of the incident.
      operationId: getIncidentStatus
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise

    put:
      tags:
        - Incidents
      summary: Update incident status
      description: Putting a new value updates the incident status.
      operationId: updateIncidentStatus
      security:
        - oauth2:
            - cnx_manage_incidents
            - css_manage_incidents_for_advanced_reseller_enterprise


  '/incidents/{incident_id}/attachments':
    get:
      tags:
        - Attachments
      summary: Incident attachments.
      description: |
        This resource contains metadata of attachments uploaded when the incident was being created.
        Incident attachments are actually associated with the initial activity. Maximum number of attachments - 3.
      operationId: getIncidentAttachments
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise

    post:
      tags:
        - Attachments
      summary: Upload incident attachment.
      description: Upload a file to attach to the incident. The attachment is linked to the initial activity.
      operationId: uploadIncidentAttachment
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise

  '/incidents/{incident_id}/attachments/{attachment_id}':
    get:
      tags:
        - Attachments
      summary: Download incident attachment.
      description: |
        This resource contains file content of the attachment identified by attachment_id.
        Incident attachments are actually associated with the initial activity.Maximum number of attachments - 3.
      operationId: getIncidentAttachment
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise

  '/incidents/{incident_id}/activities':
    # There is no get. Activities are loaded together with incident.
    post:
      tags:
        - Activities
      summary: Create new activity.
      operationId: createIncidentActivity
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise

  '/incidents/{incident_id}/activities/{activity_id}/status':
    get:
      tags:
        - Activities
      summary: Get activity status.
      operationId: getIncidentActivityStatus
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise
    put:
      tags:
        - Activities
      summary: Get activity status.
      operationId: updateIncidentActivityStatus
      security:
        - oauth2:
            - cnx_manage_incidents
            - css_manage_incidents_for_advanced_reseller_enterprise

  '/incidents/{incident_id}/activities/{activity_id}/attachments':
    post:
      tags:
        - Attachments
      summary: Upload incident activity attachment.
      description: Upload a file to attach to the specified activity.
      operationId: uploadIncidentActivityAttachment
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise

  '/incidents/{incident_id}/activities/{activity_id}/attachments/{attachment_id}':
    get:
      tags:
        - Attachments
      summary: Download incident activity attachment.
      description: This resource contains file content of the activity attachment.
      operationId: getIncidentActivityAttachment
      security:
        - oauth2:
            - cnx_log_incident_2
            - css_manage_incidents_for_advanced_reseller_enterprise
  '/incidents/getVIPIncidentCount/{organization_id}':
    get:
      tags: 
        - Incidents
      summary: Get VIP Incident for Premium Operator.
      description: This resource contains a complete representation of an VIP Incident count for current Month.
      operationId: getVIPIncidentCount
      security:
        - oauth2:
            - css_premium_csp_incident_for_operators         
components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: 'The External Incidents API uses OAuth2 and OIDC for authentication and authorization.'
      flows:
        password:
          tokenUrl: '/iot/api/auth/token'
          scopes:
            cnx_log_incident_2: 'Grants access to view and create incidents information by operator users.'
            css_manage_incidents_for_advanced_reseller_enterprise: 'Grants access to view, create and update incidents information by reseller users.'
            cnx_manage_incidents: 'Grants access to manage incidents information by operator users.'
            css_premium_csp_incident_for_operators: 'Enables premium CSPs to create VIP Incidents compared to the standard incident severity matrix' 
